language: java
jdk:
  - oraclejdk8
script:
  - mvn test
notifications:
  slack: simpleins:kQNRJhnUsV83K05WfeAGU4Kc
  email:
    recipients:
      - dpaterson1@scythe.ac.uk
      - tdwhite1@scythe.ac.uk
    on_success: change
    on_failure: change
